#!/bin/fish

# remove build caches generated by Elm compiler
rm -v packages/*/artifacts.dat

# remove documentation generated by Elm compiler
rm -v packages/*/docs.json

# and keep all other files because I might have changed them on purpose
